language: java

jdk:
  - oraclejdk7
  - openjdk7

env:
  global:
    - NEXUS_USERNAME=travis
    - secure: "GpL22H41amAWOlJSGioeENRoMzULHn6j8ahCDOVH11BjBWxpuuslWU7LzYPOWw4xm5tX7FbjqkKk8YuOAS6/MY6798lX+k98amY2S+fQ9uJl/n/RlYjMwTHg8kWwd7+CNRQCZdBR0dQKXn4XW3K2zzzko8RqqlYbELaDuTqy7ZQ="
    
after_success:
  - "[ $TRAVIS_JDK_VERSION == \"openjdk7\" ] && { python src/test/resources/write-travis-maven-settings.py; mvn -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true clean deploy --settings ~/.m2/travis-settings.xml; };"

